name: Run Build Script

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run build script
        run: ./build-multi.sh v1.32.13 --golang-version 1.25.0 --registry ghcr.io/it-compiles-lets-sell-it/k8s --arch amd64 --push
