name: Run Build Script

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build script
        run: ./build-multi.sh v1.32.13 --golang-version 1.25.0 --registry ghcr.io/it-compiles-lets-sell-it/k8s --arch amd64 --push

      - name: Build kubelet
        run: ./build-kubelet-deb.sh --release-ref v0.17.10

      - name: Upload deb package
        run: ls *.deb
